name: chat_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  firebase_analytics: ^12.0.1
  firebase_database: ^12.0.1
  firebase_auth: ^6.1.0
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  injectable: ^2.5.1
  freezed_annotation: ^3.1.0
  talker_flutter: ^5.0.1
  talker_bloc_logger: ^5.0.1
  talker_dio_logger: ^5.0.1
  dio: ^5.9.0
  auto_route: ^10.1.2
  build_runner: ^2.5.4
  freezed: ^3.1.0
  auto_route_generator: ^10.1.0
  flutter_gen_runner: ^5.12.0
  flutter_screenutil: ^5.9.3
  talker: ^5.0.1
  lottie: ^3.3.2
  injectable_generator: ^2.7.0
  shimmer: ^3.0.0
  auto_size_text: ^3.0.0
  flutter_localization: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/icons/
    - assets/lottie/

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false
      style: dot-delimiter
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/colors/color.xml